//! # lit-ui — a typed Rust DSL over the Lit web-component **primitives** kit.
//!
//! Every UI concept is a plain Rust struct whose setter + render code is
//! generated by `#[derive(UiComponent)]` (see the `lit-ui-macros` crate).
//! You configure it through method-chaining (Vaadin-style), then call
//! [`Component::render`] to get the equivalent HTML string.
//!
//! ```ignore
//! use lit_ui::prelude::*;
//!
//! let markup = button()
//!     .label("Save")
//!     .variant(Variant::Primary)
//!     .render();
//! assert!(markup.starts_with("<ui-button"));
//! ```
//!
//! ## Design principles
//!
//! * **Derive-driven** — no hand-written setter/render boilerplate.
//! * **String rendering** — [`Component::render`] returns an owned `String`.
//!   Perfect for Axum / Askama / minijinja handlers or SSE streams.
//! * **Web-component parity** — every attribute maps 1:1 to an HTML
//!   attribute read by the corresponding `<ui-*>` Lit element.
//! * **Primitives only** — this crate intentionally exposes leaf building
//!   blocks. Layout and containers live in the Lit `<ui-columns>` /
//!   `<ui-stack>` / `<ui-grid>` / `<ui-sidebar>` / `<ui-center>` /
//!   `<ui-cluster>` web components; compose them in HTML/templates,
//!   not in Rust.

// Make `::lit_ui::…` resolve inside this crate itself. Our derive macros
// emit absolute paths like `::lit_ui::core::Attr`, which normally only
// downstream crates can see. This alias lets the same generated code
// compile both here and in consumer crates without special-casing.
extern crate self as lit_ui;

pub mod core;
pub mod components;

// Re-export the derive macros so consumers write
//     use lit_ui::{UiComponent, AttrEnum};
// without needing a direct dependency on the `lit-ui-macros` crate.
pub use lit_ui_macros::{AttrEnum, UiComponent};

/// Re-exports the everyday pieces you want in scope.
///
/// A single `use lit_ui::prelude::*;` brings in every free-function
/// constructor and every enum you need to compose primitives.
pub mod prelude {
    // Core rendering primitives.
    pub use crate::core::{Component, Node, RenderExt};

    // Derive macros — most callers won't `#[derive]` these themselves,
    // but re-exporting them here means downstream crates that DO want to
    // build extra primitives don't need to add `lit-ui-macros` as a dep.
    pub use crate::{AttrEnum, UiComponent};

    // Form inputs
    pub use crate::components::button::{button, Button, Variant, Size, ButtonType};
    pub use crate::components::input::{input, Input, InputType};
    pub use crate::components::select::{select, Select, SelectOption};
    pub use crate::components::checkbox::{checkbox, Checkbox};
    pub use crate::components::radio::{radio, radio_group, Radio, RadioGroup};
    pub use crate::components::switch::{switch, Switch};
    pub use crate::components::datepicker::{datepicker, Datepicker};
    pub use crate::components::daterange::{date_range, DateRange};

    // Atomic display
    pub use crate::components::icon::{icon, Icon, IconName, Icons, IntoIconName};
    pub use crate::components::badge::{badge, Badge, Tone};
    pub use crate::components::avatar::{avatar, Avatar, AvatarSize};
    pub use crate::components::tooltip::{tooltip, Tooltip, Placement};
    pub use crate::components::skeleton::{skeleton, Skeleton, Shape as SkeletonShape};

    // Utility / feedback primitives
    pub use crate::components::slider::{slider, Slider};
    pub use crate::components::progress::{progress, Progress, ProgressTone};
    pub use crate::components::color_swatch::{color_swatch, ColorSwatch, SwatchSize};
    pub use crate::components::theme_toggle::{theme_toggle, ThemeToggle};

    // Top-level document envelope.
    pub use crate::components::page::{page, Page};
}
